config/routes.rb
Rails.application.routes.draw do

  root "home#intro"

  get 'agreement' => 'mobile#agreement'
  get 'privacy' => 'mobile#privacy'
  get 'support' => 'mobile#support'
  get 'admission' => "home#admission"
  get 'join' => 'home#join'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def intro
    
  end
  
  def admission
     
  end
  
  def join
    
  end
  
  def recruit
    @recruit = Recruit.new
  end
  
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  
  layout "mobile"
  
  def agreement
    
  end
  
  def privacy
    
  end
  
  def support
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/admission.html.erb
<div class="gh-admission-main">
	<div class="container">
		<h1>光合音乐入场券</h1>
		<p class="lead">一个月最难忘的音乐经历，迈出音乐旅程的第一步<br />面对梦想，这一次我们将不遗余力</p>
	</div>
</div>
<div class="gh-admission-feature">
	<div class="container">
		<h2>30天的极限挑战，光合音乐成长任务</h2>
		<p class="lead">和粉丝共同完成的音乐任务，最真实地还原音乐道路上的点点滴滴<br /></p>
		<hr />
		<div class="gh-admission-item row">
			<div class="col-sm-6">
				<h3 class="gh-admission-title">“过去音乐人遇到的最大难题就是如何迈出第一步，<br />光合入场券希望通过精心设计的六个任务<br />让每一个音乐人顺利启程。”</h3>
				<%= image_tag "gh-fanspal-usercase.jpg", :class => "img-responsive" %>
			</div>
			<div class="col-sm-6">
				<div class="gh-timeline-container">
						<div class="gh-timeline-major">
							<a class="btn btn-lg btn-outline">第0天：初出茅庐</a>
						</div>
						<div class="gh-timeline-minor">
							<h4>选择5首个人作品上传，总人气值到达1000，解锁光合小伙伴</h4>
						</div>
						<div class="gh-timeline-major">
							<a class="btn btn-lg btn-outline">第3天：百里挑一</a>
						</div>
						<div class="gh-timeline-minor">
							<h4>通过实名认证，总人气值达到2000，解锁我的音乐制作团队</h4>
						</div>
						<div class="gh-timeline-major">
							<a class="btn btn-lg btn-outline">第8天：一鸣惊人</a>
						</div>
						<div class="gh-timeline-minor">
							<h4>升级第一张绿卡，总人气值达到4000，解锁第一支音乐视频</h4>
						</div>
						<div class="gh-timeline-major">
							<a class="btn btn-lg btn-outline">第12天：再接再厉</a>
						</div>
						<div class="gh-timeline-minor">
							<h4>升级第二张绿卡，总人气值达到6000，解锁第二支音乐视频</h4>
						</div>
						<div class="gh-timeline-major">
							<a class="btn btn-lg btn-outline">第18天：整装待发</a>
						</div>
						<div class="gh-timeline-minor">
							<h4>所有作品升级到绿卡，总人气值达到10000，解锁在线演唱会</h4>
						</div>
						<div class="gh-timeline-major">
							<a class="btn btn-lg btn-outline">第25天：小有所成</a>
						</div>
						<div class="gh-timeline-minor">
							<h4>完成在线演唱会，总人气值达到15000，解锁演唱会视频</h4>
						</div>
				</div>
			</div>
		</div>
		<hr />
		<h2>超乎想象的音乐服务，和我们一起全力以赴</h2>
		<p class="lead">对于创造好音乐，我们和你一样精益求精</p>
		<div class="row">
			<div class="col-sm-4 gh-service-item">
				<%= image_tag "gh-service-p1.png", :class => "img-responsive" %>
				<div class="gh-service-caption">
					<h3>金牌制作团队</h3>
					<p>由光合精选的制作团队做你最坚实的后援</p>
				</div>
			</div>
			<div class="col-sm-4 gh-service-item">
				<%= image_tag "gh-service-p2.png", :class => "img-responsive" %>
				<div class="gh-service-caption">
					<h3>光合之家</h3>
					<p>音乐需要听众，也需要一个温暖的家</p>
				</div>
			</div>
			<div class="col-sm-4 gh-service-item">
				<%= image_tag "gh-service-p3.png", :class => "img-responsive" %>
				<div class="gh-service-caption">
					<h3>光合小伙伴</h3>
					<p>让你的音乐之旅永远不会孤军奋战</p>
				</div>
			</div>
		</div>
		<hr />
		<h2>精心设计的粉丝互动体验，光合音乐粉丝宝</h2>
		<p class="lead">最方便的粉丝互动工具，把每一份粉丝心意汇聚在此</p>
		<hr />
		<div class="row">
			<div class="col-sm-4">
				<%= image_tag "gh-fanspal-f1.png" %>
				<h4>全平台聚合</h4>
				<p>通过二维码，在各个平台上锁定核心粉丝汇聚在此</p>
			</div>
			<div class="col-sm-4">
				<%= image_tag "gh-fanspal-f2.png" %>
				<h4>无需众筹</h4>
				<p>粉丝点赞，你来做歌，让粉丝和你一起成长</p>
			</div>
			<div class="col-sm-4">
				<%= image_tag "gh-fanspal-f3.png" %>
				<h4>粉丝大数据</h4>
				<p>谁是铁杆粉丝，粉丝最喜欢哪首歌，种种难题不再迷茫</p>
			</div>
		</div>
		<hr />
	</div>
</div>

app/views/home/intro.html.erb
<div id="content" class="gh-intro-main">
	<div class="container">
		<h1>音乐复兴</h1>
		<p class="lead hidden-xs">我们是信息时代的唱片公司，致力于通过互联网打造新时代的好音乐<br />再现音乐市场的繁荣和兴旺</p>
		<p class="lead visible-xs">我们是信息时代的唱片公司<br />致力于通过互联网打造新时代的好音乐<br />再现音乐市场的繁荣和兴旺</p>
		<p class="lead visible-xs">光合音乐</p>
	</div>
</div>
<div class="gh-intro-feature">
	<div class="container">
		<h2 class="hidden-xs">每个人都是音乐的创造者</h2>
		<h3 class="visible-xs">每个人都是音乐的创造者</h3>
		<p class="lead hidden-xs">没有繁琐的经纪合约，光合音乐致力于服务每一位心怀梦想的音乐人<br />我们相信互联网让每个好音乐正在发声</p>
		<p class="lead visible-xs">没有繁琐的经纪合约<br />光合音乐致力于服务<br />每一位心怀梦想的音乐人</p>
		<p class="lead visible-xs">我们相信互联网让每个好音乐<br />正在发声</p>
		<hr/>
		<div class="row">
			<div class="col-sm-4">
				<%= image_tag "gh-logo-lv1.png" %>
				<h4>光合入场券</h4>
				<p>为早期音乐人量身打造的一个月孵化计划，匹配你的第一位制作人，打磨第一只作品以及培养第一批忠实听众</p>
			</div>
			<hr class="visible-xs" />
			<div class="col-sm-4">
				<%= image_tag "gh-logo-lv2.png" %>
				<h4>光合成长计划</h4>
				<p>为成长期的音乐人定制的三个月成长计划，全力打造属于你的第一张EP作品，成为你音乐道路上的一步飞跃</p>
			</div>
			<hr class="visible-xs" />
			<div class="col-sm-4">
				<%= image_tag "gh-logo-lv3.png" %>
				<h4>光合加速计划</h4>
				<p>为加速期的音乐人定制的六个月成长计划，实现首张个人专辑的全国发行和巡演计划，你的粉丝在等待你</p>
			</div>
		</div>
		<hr />
		<p class="lead">光合音乐面向全国的优秀音乐人开放第一批入场券，限量68张</p>
		<a class="btn btn-outline btn-lg" href="<%= admission_path %>">详细了解光合入场券</a>
	</div>
</div>
<div class="gh-intro-feature">
	<div class="container">
		<h2 class="hidden-xs">激活你的音乐能量</h2>
		<h3 class="visible-xs">激活你的音乐能量</h3>
		<p class="lead">在快速发展的信息时代，拥有传播能量的好音乐才能唤醒听众的耳朵<br />光合音乐专注于挖掘和制作最有能量的音乐内容，引爆互联网</p>
		<div class="row">
			<div class="col-xs-4 col-sm-2 feature-item">
				<h2><span class="glyphicon glyphicon-phone"></span></h2>
				<h4>移动优先</h4>
			</div>
			<div class="col-xs-4 col-sm-2 feature-item">
				<h2><span class="glyphicon glyphicon-user"></span></h2>
				<h4>金牌制作</h4>
			</div>
			<div class="col-xs-4 col-sm-2 feature-item">
				<h2><span class="glyphicon glyphicon-globe"></span></h2>
				<h4>全网推广</h4>
			</div>
			<div class="col-xs-4 col-sm-2 feature-item">
				<h2><span class="glyphicon glyphicon-thumbs-up"></span></h2>
				<h4>人气为王</h4>
			</div>
			<div class="col-xs-4 col-sm-2 feature-item">
				<h2><span class="glyphicon glyphicon-certificate"></span></h2>
				<h4>信用担保</h4>
			</div>
			<div class="col-xs-4 col-sm-2 feature-item">
				<h2><span class="glyphicon glyphicon-gift"></span></h2>
				<h4>周边开发</h4>
			</div>
		</div>
		<hr />
		<p class="lead">光合音乐与大家一起释放音乐能量</p>
		<a class="btn btn-outline btn-lg" href="<%= join_path %>">申请加入光合音乐</a>
	</div>
</div>

<% content_for :scripts do %>
<script>
$(function(){
	$('.alert').hide();
});
</script>
<% end %>

app/views/home/join.html.erb
<div class="gh-recruit-main">
	<div class="container">
		<h1>互联网·音乐·革命<br />已经来临</h1>
		<p class="lead">机遇·挑战</p>
		<hr />
		<p class="lead">作为信息时代的唱片公司<br />我们相信在下一个音乐时代<br />需要勇于突破传统的你</p>
		<p class="lead">光合音乐</p>
		<p>地址：北京市海淀区五道口华清嘉园甲5号楼</p>
        <p>您有任何问题，请发邮件到</p>
        <p>邮箱：party@fanheapp.com</p>
	</div>
</div>
<div class="gh-recruit-main default">
	<div class="container">
		<h3>高级前端工程师：</h2>
        <p style="margin-top: 30px;">工作内容：</p>
        <p>负责产品Web端（爪机&本子）页面开发</p>
        <p style="margin-top: 50px;">技能要求：</p>
        <p>1、熟悉html5, css3；</p>
        <p>2、熟悉Javascript、熟悉JQuery或ExtJS或其他JS开发框架；</p>
        <p>3、了解各主流浏览器（爪机&本子）间的兼容性和适配问题；</p>
        <p>4、熟悉backbonejs, angularjs或knockoutjs其中的一种；</p>
        <p>5、熟悉前端的图片浏览相关功能及优化；</p>
        <p style="margin-top: 50px;">加分技能：</p>
        <p>1、了解AVOS cloud (Lean cloud) / 环信等类似云服务；</p>
        <p>2、具备UE/UI设计能力优先。</p>
	</div>
</div>
<div class="gh-recruit-main red">
	<div class="container">
		<h3>Android开发工程师：</h3>
        <p style="margin-top: 30px;">工作内容：</p>
        <p>负责饭盒产品的Android开发；</p>
        <p style="margin-top: 50px;">技能要求：</p>
        <p>1、对安卓手机应用开发有较好的理解；</p>
        <p>2、对安卓交互动画设计与实现有较深的思考；</p>
        <p>3、对媒体、社交产品及相关的数据模型逻辑有较好的理解；</p>
        <p>4、对数据库相关知识有良好的了解；</p>
        <p style="margin-top: 50px;">加分技能：</p>
        <p>1、了解AVOS Cloud (lean cloud)、环信等类似云服务相关开发；</p>
        <p>2、了解html在手机端的适配。</p>
	</div>
</div>
<div class="gh-recruit-main blue">
	<div class="container">
		<h3>产品运营：</h3>
        <p style="margin-top: 30px;">工作内容：</p>
        <p>1、参与饭盒的产品运营；</p>
        <p>2、饭盒产品运营活动的企划与执行；</p>
        <p>3、为产品的迭代优化提出建议；</p>
        <p style="margin-top: 50px;">技能要求：</p>
        <p>1、了解社区类产品的运营，有产品运营经验；</p>
        <p>2、对于图片类社交媒体有良好的理解；</p>
        <p>3、对于时下流行的娱乐偶像及粉丝行为有一定的了解及接受度；</p>
        <p>4、对于亚文化圈层有一定的了解及接受度；</p>
        <p style="margin-top: 50px;">加分技能：</p>
        <p>1、了解微博粉丝圈的玩法；）</p>
        <p>2、懂一点UE/UI设计也不错啊；D</p> 
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "光合音乐" %></title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
    	<div class="navbar-header">
    		<h3 class="visible-xs" style="text-align: center; margin: 0px auto; width: 108px;">
      			<a class="guanghe-logo text-hide" href="#">光合音乐</a>
      		</h3>
      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".gh-nav-collapse">
        		<span class="sr-only">Toggle navigation</span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
      		</button>
    	</div>
    	<ul class="nav navbar-nav hidden-xs">
    		<li><a href="<%= root_path %>">首页</a></li>
    		<li><a href="http://fanheapp.com">饭盒~</a></li>
    		<li><a href="<%= admission_path %>">光合音乐入场券</a></li>
    		<li><a href="<%= join_path %>">加入我们</a></li>
    	</ul>
    	<h3 class="hidden-xs" style="text-align: center; margin: 0px auto; width: 108px;">
      		<a class="guanghe-logo text-hide" href="#">光合音乐</a>
      	</h3>
    	<div class="collapse navbar-collapse gh-nav-collapse">
    		<ul class="nav navbar-nav visible-xs">
    			<li><a href="<%= root_path %>">首页</a></li>
    			<li><a href="http://fanheapp.com">饭盒~</a></li>
    			<li><a href="<%= admission_path %>">光合音乐入场券</a></li>
    			<li><a href="<%= join_path %>">加入我们</a></li>
    		</ul>
    	</div>
	</div>
	</nav>
	
	<div class="container">
	<% if notice %>
	<div data-alert class="alert alert-info col-md-8 col-md-offset-2" id="notice-panel">
		<%= notice %>
	</div>
	<% end %>
	<% if alert %>
	<div data-alert class="alert alert-danger col-md-8 col-md-offset-2" id="alert-panel">
		<%= alert %>
	</div>
	<% end %>
	</div>
	
	<%= yield %>
	
	<div class="footer">
		<div class="container">
			<div class="copyright">
				<span class="filings">
					京ICP备14014730号-1
				</span>
				<br class="visible-xs" />
				 © 2013-2014 光合音乐 版权所有
			</div>
		</div>
	</div>
	
	<%= yield :scripts %>

</body>
</html>

app/views/layouts/mobile.html.erb
<%= yield %>

app/views/mobile/privacy.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>无标题文档</title>
		<style>
			.k_mm {
				margin: 0 10px;
			}
			.k_mm h1 {
				text-align: center;
				font-size: 18px;
			}
			.k_mm h2 {
				font-size: 16px;
			}
			.k_mm p {
				font-size: 12px;
				line-height: 2;
			}
		</style>
	</head>
	<body>
		<div class="k_mm">
			<h1> 个人信息及隐私保护政策 </h1>
			<h2> 1 总则
			<br />
			</h2>
			<p>
				本《个人信息及隐私保护政策》将详细说明饭盒在获取、管理及保护用户个人信息方面的政策及措施。本《个人信息及隐私保护政策》适用于饭盒向您提供的所有服务，无论您是通过计算机设备、移动终端或其他设备获取饭盒服务。
			</p>
			<h2> 2 个人信息的收集
			<br />
			</h2>
			<p>
				2.1 您已知悉且同意，在您注册饭盒帐号或使用饭盒提供的服务时，饭盒将记录您提供的相关个人信息，如：姓名、手机号码、饭盒所支持的第三方登陆账号等，上述个人信息是您获得饭盒提供服务的基础。同时，基于优化用户体验之目的，饭盒会获取与提升饭盒服务有关的其他信息，例如当您访问饭盒时，我们可能会收集哪些服务的受欢迎程度、访问的时间、地点等以便优化我们的服务。
			</p>
			<h2> 3 个人信息的管理
			<br />
			</h2>
			<p>
				3.1 为了向您提供更好的服务或产品，饭盒会在下述情形使用您的个人信息：
			</p>
			<p>
				3.1.1 根据相关法律法规的要求；
			</p>
			<p>
				3.1.2 根据您的授权；
			</p>
			<p>
				3.1.3 根据饭盒相关服务条款、应用许可使用协议的约定。
			</p>
			<p>
				3.2 您已知悉并同意：在现行法律法规允许的范围内，饭盒可能会将您非隐私的个人信息用于市场营销，使用方式包括但不限于：在饭盒平台中向您展示或提供广告和促销资料，向您通告或推荐饭盒的服务或产品信息，以及其他此类根据您使用饭盒服务或产品的情况所认为您可能会感兴趣的信息。其中也包括您在采取授权等某动作时选择分享的信息，例如当您在使用饭盒过程中所使用的人物、事件、地点等的称呼及表达方式等。
			</p>
			<p>
				3.3 未经您本人允许，饭盒不会向任何第三方披露您的个人信息，下列情形除外：
			</p>
			<p>
				3.3.1 饭盒已经取得您或您监护人的授权；
			</p>
			<p>
				3.3.2 司法机关或行政机关及相关监管部门机构基于法定程序要求饭盒披露的；
			</p>
			<p>
				3.3.3 饭盒为维护自身合法权益而向用户提起诉讼或仲裁时；
			</p>
			<p>
				3.3.4 根据您与饭盒相关服务条款、应用许可使用协议的约定；
			</p>
			<p>
				3.3.5 法律法规规定的其他情形。
			</p>
			<h2> 4 个人信息的保护
			<br />
			</h2>
			<p>
				4.1 饭盒将尽一切合理努力保护其获得的用户个人信息。为防止用户个人信息在意外的、未经授权的情况下被非法访问、复制、修改、传送、遗失、破坏、处理或使用，饭盒将采取以下措施保护您的个人信息：
			</p>
			<p>
				4.1.1 以适当的方式对用户的个人信息进行加密处理；
			</p>
			<p>
				4.1.2 在适当的位置使用密码对用户个人信息进行保护；
			</p>
			<p>
				4.1.3 限制对用户个人信息的访问；
			</p>
			<p>
				4.1.4 其他的合理措施。
			</p>
			<p>
				4.2 尽管已经采取了上述合理有效措施，并已经遵守了相关法律规定要求的标准，但饭盒仍然无法保证您的个人信息通过不安全途径进行交流时的安全性。因此，用户个人应采取积极措施保证个人信息的安全，如：定期修改帐号密码，不将自己的帐号密码等个人信息透露给他人。
			</p>
			<p>
				4.3 您知悉：饭盒提供的个人信息及隐私保护措施仅适用于饭盒平台，一旦您离开饭盒，浏览或使用其他网站、服务及内容资源，饭盒即没有能力及义务保护您在饭盒以外的网站提交的任何个人信息，无论您登陆或浏览上述网站是否基于饭盒的链接或引导。
			</p>
			<h2> 5 对未成年人个人信息的特别保护
			<br />
			</h2>
			<p>
				5.1 饭盒非常重视对未成年人个人信息的保护。若您是18周岁以下的未成年人，在使用饭盒的服务前，应确保事先取得监护人的同意，如您在饭盒上申请注册账号，饭盒将默认为您已得到前述同意。饭盒将根据国家相关法律法规及本《个人信息及隐私保护政策》的规定保护未成年人的个人信息。
			</p>
			<h2> 6 隐私保护政策的修改
			<br />
			</h2>
			<p>
				6.1 饭盒有权随时修改《个人信息及隐私保护政策》的任何条款，一旦《个人信息及隐私保护政策》的内容发生变动，饭盒将会直接在饭盒网站上公布修改之后的《个人信息及隐私保护政策》，该公布行为视为饭盒已经通知您修改内容。饭盒也可通过其他适当方式向用户提示修改内容。如果您不同意饭盒对本《个人信息及隐私保护政策》相关条款所做的修改，您有权停止使用饭盒服务。如果您继续使用饭盒服务，则视为您接受饭盒对本协议相关条款所做的修改。
			</p>
		</div>
	</body>

app/views/mobile/support.html.erb
<html><head><title>正在跳转</title></head>
<body>
	<script language='javascript'>document.location = 'http://www.guanghemusic.com'</script>
</body>
</html>